language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode12.5
      rvm: system

env:
  global:
    - HOMEBREW_DEVELOPER=1

before_install:
  - brew update || brew update
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - mkdir -p $(brew --repo)/Library/Taps/denji
  - ln -s $PWD $(brew --repo)/Library/Taps/denji/homebrew-nginx
  - cd $(brew --repo)/Library/Taps/denji/homebrew-nginx
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/denji/homebrew-nginx"
  - ulimit -n 1024
  - umask 022

script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
